config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from explorea.events import views

urlpatterns = [
    path('home/', views.index, name='index'),
	path('events/', include('explorea.events.urls', namespace='events')),
	path('accounts/', include('explorea.accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
]

# in production a dedicated server is used to serve media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

explorea/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf.urls import url 
from . import views

app_name = 'accounts' 

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/events/'), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('change-password/', views.change_password, name='change_password'),
    path('reset-password/', auth_views.PasswordResetView.as_view(template_name='accounts/reset_password.html', 
        email_template_name='accounts/reset_password_email.html'), 
        name='reset_password'),
    path('reset-password/done/', auth_views.PasswordResetDoneView.as_view(),  
        name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 
        auth_views.PasswordResetConfirmView.as_view(), 
        name='password_reset_confirm'),
	path('reset-password/complete/', 
        auth_views.PasswordResetCompleteView.as_view(), 
        name='password_reset_complete'),
 
]

explorea/events/urls.py
from django.urls import path

from . import views

app_name = 'events'

urlpatterns = [
	path('', views.event_listing, name='events'),
	path('search/', views.event_search, name='search'),

	path('detail/<slug:slug>/', views.event_detail, name='detail'),
	path('update/<slug:slug>/', views.update_event, name='update_event'),
	path('delete/<slug:slug>/', views.delete_event, name='delete_event'),

	#path('eventruns/', views.eventRun_listing, name='eventruns'),
	path('mine/', views.myevents_listing, name='myevents'),
	path('new/', views.create_event, name='create_event'),


	path('eventRun/new/', views.create_eventrun, name='create_eventrun'),
	path('updateRun/<int:pk>/', views.update_eventrun, name='update_eventrun'),
	path('deleteRun/<int:pk>/', views.remove_eventrun, name='remove_eventrun'),

	path('<category>/', views.event_listing, name='events_by_category'),
	]

explorea/accounts/models.py
from django.db import models
from django.conf import settings

def image_dir(instance, filename):
    return 'user_{}/profile_{}'.format(instance.user.id, filename)

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE, primary_key=True)
    is_host = models.BooleanField(default=False)
    about = models.TextField(max_length=500)
    avatar = models.ImageField('Upload your photo', 
        upload_to=image_dir, null=True)

explorea/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from core.validators import validate_human_name

from .models import Profile

UserModel = get_user_model()

class RegisterForm(UserCreationForm):
    # cutom made validator
    first_name = forms.CharField(max_length=100, validators=[validate_human_name,])
    last_name = forms.CharField(max_length=100, validators=[validate_human_name,])
    
    class Meta:
        model = UserModel 
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
        ]

class EditUserForm(UserChangeForm):
    first_name = forms.CharField(max_length=100, validators=[validate_human_name,])
    last_name = forms.CharField(max_length=100, validators=[validate_human_name,])
    
    class Meta:
        model = UserModel
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
            'password'
        ]

class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['about', 'avatar',]

explorea/events/forms.py
from django import forms

from .models import Event, EventRun
from django.utils import timezone

class EventForm(forms.ModelForm):

    class Meta:
        model = Event
        fields = [
            'name',
            'description',
            'location',
            'category',
            'thumbnail',
            'main_image',
        ]

    exclude = ['host', 'slug']

class EventRunForm(forms.ModelForm):
    date = forms.DateField(input_formats=["%d.%m.%Y"], widget=forms.DateInput(format = '%d.%m.%Y'))

    class Meta:
        model = EventRun
        fields = [
          'event',
            'date',
            'time',
            'seats_available',
            'price',
        ]

class EventFilterForm(forms.Form):
    PRICE_ASC='price'
    PRICE_DESC='-price'
    SEATS='-seats_available'
    DATE='date'
    NAME='event__name'
    HOST='event__host__username'

    SORT_CHOICES = (
        (PRICE_ASC, 'cheapest'),
        (PRICE_DESC, 'most expensive'),
        (SEATS,'seats available'),
        (DATE,'date'),
        (NAME,'name'),
        (HOST, 'host'),
    )

    date_from = forms.DateField(label="From", initial=None,
     widget=forms.SelectDateWidget, required=False)
     
    date_to = forms.DateField(label="To", initial=None,
        widget=forms.SelectDateWidget, required=False)
        
    guests = forms.IntegerField(required=False, min_value=1)

    sort_by = forms.ChoiceField(label="Sort by", choices=SORT_CHOICES, 
        required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.initial['sort_by'] = 'date'

    def clean(self):
        super().clean()
        date_from = self.cleaned_data.get('date_from')
        date_to = self.cleaned_data.get('date_to')

        if ((date_from and date_to) and 
             date_from > date_to):
            self.add_error('date_from', 'Date selected later than date To')
        
        for name, date in [('date_from',date_from), 
                     ('date_to', date_to)]:
            if date and date < timezone.now().date():
                self.add_error(name, 'Selected date in the past')

        if not self.cleaned_data.get('sort_by'):
            self.cleaned_data['sort_by'] = 'date'
        self.cleaned_data

class MultipleFileForm(forms.Form):
    gallery = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)

explorea/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model, authenticate, login, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required

from .forms import RegisterForm, EditProfileForm, EditUserForm

@login_required
def profile(request):
	return render(request, 'accounts/profile.html')


def register(request):
    if request.method == 'POST':

        form = RegisterForm(request.POST)

        if form.is_valid():
            user = form.save()

            raw_password = form.cleaned_data.get('password1')
            
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)

            return redirect('profile')
        else:
            return render(request, 'accounts/register.html', {'form': form})

    form = RegisterForm()
    return render(request, 'accounts/register.html', {'form': form} )


@login_required
def edit_profile(request):
    user_form = EditUserForm(request.POST or None, instance=request.user)
    # getting the image from the form with request.FILES
    profile_form = EditProfileForm(request.POST or None, request.FILES or None, instance=request.user.profile)

    if request.method == 'POST':

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save()
            return redirect('accounts:profile')

    return render(request, 'accounts/edit_profile.html', 
        {'user_form': user_form, 'profile_form': profile_form})


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('/accounts/profile/')
        else:
            return render(request, 'accounts/change_password.html', {'form': form})

    form = PasswordChangeForm(user=request.user)
    return render(request, 'accounts/change_password.html', {'form': form})

explorea/events/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.views.generic import ListView

from .models import Event, EventRun , Album, Image
from .forms import EventForm, EventRunForm, EventFilterForm, MultipleFileForm

def index(request):
	return render(request, 'events/index.html')


def event_listing(request, category=None):

    event_runs = EventRun.objects.all().filter_by_category(category)
    filter_form =  EventFilterForm(request.GET or None)
    
    if request.GET and filter_form.is_valid():
        data = filter_form.cleaned_data
    else:
        data = {}
    
    event_runs = event_runs.filter_first_available(**data)

    paginator = Paginator(event_runs, 4)
    page = request.GET.get('page')
    event_runs = paginator.get_page(page)

    return render(request, 'events/event_listing.html', 
        {'event_runs': event_runs, 'filter_form': filter_form})


def event_search(request):
    query = request.GET.get('q')
    events = Event.objects.search(query)

    filter_form =  EventFilterForm()
    paginator = Paginator(events, 4)
    page = request.GET.get('page')
    events = paginator.get_page(page)

    return render(request, 'events/event_listing.html', 
        {'events': events, 'filter_form': filter_form})



'''
def eventRun_listing(request):
	eventRuns = EventRun.objects.all()
	return render(request, 'events/eventRun_listing.html', {'eventRuns' : eventRuns})
'''

def event_detail(request, slug):
    event = Event.objects.get(slug=slug)
    runs = event.active_runs()
    args = {'event': event, 'runs': runs}

    return render(request, 'events/event_detail.html', args)

@login_required
def myevents_listing(request):
	events = Event.objects.filter(host=request.user)
	return render(request, 'events/myevents_listing.html', {'events': events})

@login_required
def delete_event(request, slug):
	event = get_object_or_404(Event, slug=slug)
	event.delete()
	return HttpResponseRedirect(reverse('events:myevents'))

@login_required
def update_event(request, slug):
    event = Event.objects.get(slug=slug)
    event_form = EventForm(request.POST or None, request.FILES or None, instance=event)
    file_form = MultipleFileForm(files=request.FILES or None)

    if request.method == 'POST':
        if event_form.is_valid() and file_form.is_valid():
            event = event_form.save()

            for file in request.FILES.getlist('gallery'):
                Image.objects.create(album=event.album, image=file, title=file.name)

            return redirect(event.get_absolute_url())

    return render(request, 'events/create_event.html', 
        {'event_form': event_form, 'file_form': file_form, 'event': event})

@login_required
def create_event(request):
    event_form = EventForm(request.POST or None, request.FILES or None)
    file_form = MultipleFileForm(files=request.FILES or None)

    if request.method == 'POST':
 
        if event_form.is_valid() and file_form.is_valid():
            event = event_form.save(commit=False)
            event.host = request.user
            event.save()
            # save the individual images
            for file in request.FILES.getlist('gallery'):
                Image.objects.create(album=event.album, image=file, title=file.name)

            return redirect(event.get_absolute_url())

    return render(request, 'events/create_event.html', 
         {'event_form': event_form, 'file_form': file_form})

@login_required
def remove_eventrun(request, pk):
	eventrun = get_object_or_404(EventRun, pk=pk)
	eventrun.delete()
	return HttpResponseRedirect(reverse('events:eventRuns'))

@login_required
def update_eventrun(request, pk):
	eventrun = get_object_or_404(EventRun, pk=pk)
	if request.method == 'POST':
		form = EventRunForm(request.POST, instance=eventrun)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('events:eventRuns'))
	else:
		form = EventRunForm(instance=eventrun)
	return render(request, 'events/update_eventrun.html', {'form': form})

@login_required
def create_eventrun(request):
	if request.method == 'POST':
		form = EventRunForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('events:eventRuns'))
	else:
		form = EventRunForm()
	return render(request, 'events/create_eventrun.html', {'form': form})

explorea/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    {% block title %}

    {% endblock title %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
</head>
<body>
    {% include 'header.html' %}

  

    {% block content %}
    {% endblock content %}

    {% include 'footer.html' %}
    {% block scripts %}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script type="text/javascript">
    $(document).ready(function(){
      $('.owl-carousel').owlCarousel({
            loop:true,
            margin:10,
            nav:true,
            dots:false,
            autoHeight:true,
            autoWidth: true,
        })
    });
    </script>
    {% endblock %}
</body>
</html>

explorea/templates/footer.html
<footer>
    <section>
        <h4>LOOKING FOR</h4>
        <a href='#'>Fun</a>
        <a href='#'>Relax</a>
        <a href='#'>Experience</a>
        <a href='#'>Sights</a>
    </section>
    <section>
        <h4>MOST POPULAR</h4>
        <a href='#'>Barcelona</a>
        <a href='#'>Rome</a>
        <a href='#'>Prague</a>
        <a href='#'>London</a>
    </section>
    <section>
        <h4>ABOUT</h4>
        <a href='#'>Contact Us</a>
        <a href='#'>Our Goal</a>
        <a href='#'>Careers</a>
        <a href='#'>Terms of Service</a>
    </section>
</footer>

explorea/templates/header.html
<header>

    <div class="header-section" id="logo-container">
        <a class="nav-button" href="{% url 'index' %}">
            Explorea
        </a>
    </div>

    <div class="header-section" id="nav-buttons">
        <a class="nav-button" href="{% url 'events:events' %}">
            Events
        </a>
        <a class="nav-button" href="{% url 'events:myevents' %}">
            My Events
        </a>
        <a class="nav-button" href="#">
            Hosts
        </a>
    </div>
    
    <div class="header-section" id="header-searchbox">
        <form  action="{% url 'events:search' %}" method="GET">
            <input type="text" name='q' placeholder="search...">
        </form>
    </div>

    <div class="header-section" id="user-buttons">

   		<a class="nav-button" title="Your Cart" href="#">
            <i class="fas fa-shopping-cart"></i>
        </a>
        {# {% if user.profile.is_host %} #}
        <a class="nav-button" title="Add Event" href="{% url 'events:create_event' %}">
            <i class="fas fa-plus-circle"></i>
        </a>
        {# {% endif %} #}

        {% if user.is_authenticated %}

            <a class="nav-button" title="Profile" href="/accounts/profile/">
                {{ user.username }}
                <i class="fas fa-user"></i>
            </a>
            <a class="nav-button" href="/accounts/logout/">
                logout
            </a>

        {% else %}
            <a class="nav-button" href="/accounts/login/">
                log in
            </a>
            <a class="nav-button" href="/accounts/register/">
                sign up
            </a>
        {% endif %}
    </div>

</header>

explorea/templates/pagination.html
{% load url_tags %}

<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="{% next_page page.previous_page_number %}">&laquo;</a>
        {% endif %}

        <span class="pagination-num_pages">
        {% for page_num in page.paginator.page_range %}
            {% if page_num == page.number %}
                <a class="active-pagination" href="#">{{ page_num }}</a>
            {% else %}
                <a class="inactive-pagination" href="{% next_page page_num %}">{{ page_num }}</a>
            {% endif %}
        {% endfor %}
        </span>

        {% if page.has_next %}
            <a href="{% next_page page.next_page_number %}">&raquo;</a>
        {% endif %}
    </span>
</div>