config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from explorea.events import views

urlpatterns = [
    path('home/', views.index, name='index'),
	path('events/', include('explorea.events.urls', namespace='events')),
	path('accounts/', include('explorea.accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
]

# in production a dedicated server is used to serve media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

explorea/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf.urls import url 
from . import views

app_name = 'accounts' 

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/events/'), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('change-password/', views.change_password, name='change_password'),
    path('reset-password/', auth_views.PasswordResetView.as_view(template_name='accounts/reset_password.html', 
        email_template_name='accounts/reset_password_email.html'), 
        name='reset_password'),
    path('reset-password/done/', auth_views.PasswordResetDoneView.as_view(),  
        name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 
        auth_views.PasswordResetConfirmView.as_view(), 
        name='password_reset_confirm'),
	path('reset-password/complete/', 
        auth_views.PasswordResetCompleteView.as_view(), 
        name='password_reset_complete'),
 
]

explorea/events/urls.py
from django.urls import path

from . import views

app_name = 'events'

urlpatterns = [
	path('', views.event_listing, name='events'),
	path('search/', views.event_search, name='search'),

	path('detail/<slug:slug>/', views.event_detail, name='detail'),
	path('update/<slug:slug>/', views.update_event, name='update_event'),
	path('delete/<slug:slug>/', views.delete_event, name='delete_event'),

	#path('eventruns/', views.eventRun_listing, name='eventruns'),
	path('mine/', views.myevents_listing, name='myevents'),
	path('new/', views.create_event, name='create_event'),


	path('eventRun/new/', views.create_eventrun, name='create_eventrun'),
	path('updateRun/<int:pk>/', views.update_eventrun, name='update_eventrun'),
	path('deleteRun/<int:pk>/', views.remove_eventrun, name='remove_eventrun'),

	path('<category>/', views.event_listing, name='events_by_category'),
	]

explorea/accounts/models.py
from django.db import models
from django.conf import settings

def image_dir(instance, filename):
    return 'user_{}/profile_{}'.format(instance.user.id, filename)

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE, primary_key=True)
    is_host = models.BooleanField(default=False)
    about = models.TextField(max_length=500)
    avatar = models.ImageField('Upload your photo', 
        upload_to=image_dir, null=True)

explorea/events/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models import Max, Q, F
from django.utils import timezone
from django.utils.text import slugify

from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

def get_related_attr(obj, attrs):
    related_obj = obj
    for attr in attrs:
        related_obj = getattr(related_obj, attr)
    return related_obj

def thumbnail_image_url(instance, filename):
    '''upload_to for Event thumbnail image'''
    return 'user_{0}/thumb_{1}'.format(instance.host.id, filename) 


def main_image_url(instance, filename):
    '''upload_to for Event main image'''
    return 'user_{0}/main_{1}'.format(instance.host.id, filename)

def album_image_url(instance, filename):
    '''upload_to for Image model'''
    return 'user_{0}/{1}/{2}'.format(instance.album.event.host.id, 
        instance.album.title, filename)

# ---------------------------------------------------Event QUERY SET & MANAGER---------------------------------------------------
class EventQuerySet(models.QuerySet):
    def filter_by_category(self, category=None):
        db_equivalent = ''
        for pair in self.model.CATEGORY_CHOICES:
            if pair[1] == category:
                db_equivalent = pair[0]
                break
        else:
            return self.all()

        return self.filter(category=db_equivalent)

    def filter_available(self, date_from=None, date_to=None, guests=None):
        # filter first all the eventruns and then get the ids to events     
        date_from = date_from or timezone.now().date()

        if date_to:
            qs = EventRun.objects.filter(date__range=(date_from, date_to))
        else:
            qs = EventRun.objects.filter(date__gte=date_from)

        if guests:
            qs = qs.filter(seats_available__gte=guests)

        return self.filter(pk__in=[qs.values_list('event', flat=True)])

class EventManager(models.Manager): 
    def get_queryset(self):
        return EventQuerySet(self.model, using=self._db)

    def search(self, query=None):
        lookup = (
            Q(name__icontains=query) |
            Q(description__icontains=query) |
            Q(location__icontains=query)
        )
        return self.filter(lookup).distinct()


# ---------------------------------------------------EventRun QUERY SET & MANAGER---------------------------------------------------
class EventRunQuerySet(models.QuerySet):

    def filter_by_category(self, category=None):
        db_equivalent = ''
        for pair in Event.CATEGORY_CHOICES:
            if pair[1] == category:
                db_equivalent = pair[0]
                break
        else:
            return self.all()

        return self.filter(event__category=db_equivalent)

    def filter_available(self, date_from=None, date_to=None, guests=None):
        # filter first all the eventruns and then get the ids to events     
        date_from = date_from or timezone.now().date()

        if date_to:
            qs = self.filter(date__range=(date_from, date_to))
        else:
            qs = self.filter(date__gte=date_from)

        if guests:
            qs = qs.filter(seats_available__gte=guests)

        return qs

    def filter_first_available(self, date_from=None, date_to=None, guests=None, sort_by='date'):
        qs = self.filter_available(date_from, date_to, guests).order_by('date', 'time')

        event_ids = []
        filtered=[]
        for run in qs:
            if not run.event.id in event_ids:
                filtered.append(run)
                event_ids.append(run.event.id)

        reverse, fields = (sort_by.startswith('-'), sort_by.lstrip('-').split('__'))

        criterion = lambda obj: get_related_attr(obj, fields)

        result =  sorted(filtered, key= criterion, reverse=reverse)
        return result


class EventRunManager(models.Manager):
    
    def get_queryset(self):
        return EventRunQuerySet(self.model, using=self._db)


# ----------------------------------------Event MODEL------------------------------------------------------------------
class Event(models.Model):
    FUN = 'FN'
    RELAX = 'RX'
    EXP = 'EX'
    SIGHTS = 'SI'

    CATEGORY_CHOICES= (
        (FUN, 'fun'),
        (RELAX, 'relax'),
        (EXP, 'experience'),
        (SIGHTS, 'sights')
        )
    
    name = models.CharField(max_length=200)
    host = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=200, unique=True, null=True, blank=True)
    description = models.TextField(max_length=1000)
    location = models.CharField(max_length=500)
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default=FUN)
    created = models.DateTimeField(auto_now_add=True, null=True)
    
    thumbnail = ProcessedImageField(upload_to=thumbnail_image_url,
        processors=[ResizeToFill(300,200)],
        format='PNG',
        options={'quality':60},
        null=True,
        )
    main_image = ProcessedImageField(upload_to=main_image_url,
        processors=[ResizeToFill(500,600)],
        format='PNG',
        options={'quality':100},
        null=True,
        )

    objects = EventManager()

    def __str__(self):
    	return self.name

    def get_absolute_url(self):
        return reverse('events:detail', args=[self.slug])

    def active_runs(self):
        today = timezone.now().date()
        return self.eventrun_set.filter(date__gte=today)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name + '-with-' + self.host.username)
        super().save(*args, **kwargs)

        # create Album - alternative to use signals.py together with apps.py
        if not hasattr(self, 'album'):
            Album.objects.create(event=self)

    class Meta:
        ordering = ['name']
        unique_together = (("name", "host"),)

class EventRun(models.Model):

    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    date = models.DateField(blank=False, null=False)
    time = models.TimeField(blank=False, null=False)
    seats_available = models.PositiveIntegerField(blank=False, null=False)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=False, null=False)

    objects = EventRunManager()

    def __str__(self):
        return '{}|{} ({})'.format(self.date, self.event, self.event.category)

    class Meta:
        ordering = ['date', 'time']

# -------------------------------------------------------------------------ALBUM MODEL -------------------------------------------
class Album(models.Model):
    event = models.OneToOneField(Event, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.title:
            self.title = "album_" + self.event.name
        super().save(*args, **kwargs)

    def __str__(self):
        return '{}'.format(self.title)

# ------------------------------------------------------------------------IMAGE MODEL---------------------------------------------------
class Image(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    image = ProcessedImageField(upload_to=album_image_url,
            processors=[ResizeToFill(500,400)],
            format='PNG',
            options={'quality':80})
    title = models.CharField(max_length=200, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}/{}'.format(self.album, self.title)


    class Meta:
        ordering = ['created']

explorea/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model, authenticate, login, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required

from .forms import RegisterForm, EditProfileForm, EditUserForm

@login_required
def profile(request):
	return render(request, 'accounts/profile.html')


def register(request):
    if request.method == 'POST':

        form = RegisterForm(request.POST)

        if form.is_valid():
            user = form.save()

            raw_password = form.cleaned_data.get('password1')
            
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)

            return redirect('profile')
        else:
            return render(request, 'accounts/register.html', {'form': form})

    form = RegisterForm()
    return render(request, 'accounts/register.html', {'form': form} )


@login_required
def edit_profile(request):
    user_form = EditUserForm(request.POST or None, instance=request.user)
    # getting the image from the form with request.FILES
    profile_form = EditProfileForm(request.POST or None, request.FILES or None, instance=request.user.profile)

    if request.method == 'POST':

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save()
            return redirect('accounts:profile')

    return render(request, 'accounts/edit_profile.html', 
        {'user_form': user_form, 'profile_form': profile_form})


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('/accounts/profile/')
        else:
            return render(request, 'accounts/change_password.html', {'form': form})

    form = PasswordChangeForm(user=request.user)
    return render(request, 'accounts/change_password.html', {'form': form})

explorea/events/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.views.generic import ListView

from .models import Event, EventRun , Album, Image
from .forms import EventForm, EventRunForm, EventFilterForm, MultipleFileForm

def index(request):
	return render(request, 'events/index.html')


def event_listing(request, category=None):

    event_runs = EventRun.objects.all().filter_by_category(category)
    filter_form =  EventFilterForm(request.GET or None)
    
    if request.GET and filter_form.is_valid():
        data = filter_form.cleaned_data
    else:
        data = {}
    
    event_runs = event_runs.filter_first_available(**data)

    paginator = Paginator(event_runs, 4)
    page = request.GET.get('page')
    event_runs = paginator.get_page(page)

    return render(request, 'events/event_listing.html', 
        {'event_runs': event_runs, 'filter_form': filter_form})


def event_search(request):
    query = request.GET.get('q')
    events = Event.objects.search(query)

    filter_form =  EventFilterForm()
    paginator = Paginator(events, 4)
    page = request.GET.get('page')
    events = paginator.get_page(page)

    return render(request, 'events/event_listing.html', 
        {'events': events, 'filter_form': filter_form})



'''
def eventRun_listing(request):
	eventRuns = EventRun.objects.all()
	return render(request, 'events/eventRun_listing.html', {'eventRuns' : eventRuns})
'''

def event_detail(request, slug):
    event = Event.objects.get(slug=slug)
    runs = event.active_runs()
    args = {'event': event, 'runs': runs}

    return render(request, 'events/event_detail.html', args)

@login_required
def myevents_listing(request):
	events = Event.objects.filter(host=request.user)
	return render(request, 'events/myevents_listing.html', {'events': events})

@login_required
def delete_event(request, slug):
	event = get_object_or_404(Event, slug=slug)
	event.delete()
	return HttpResponseRedirect(reverse('events:myevents'))

@login_required
def update_event(request, slug):
    event = Event.objects.get(slug=slug)
    event_form = EventForm(request.POST or None, request.FILES or None, instance=event)
    file_form = MultipleFileForm(files=request.FILES or None)

    if request.method == 'POST':
        if event_form.is_valid() and file_form.is_valid():
            event = event_form.save()

            for file in request.FILES.getlist('gallery'):
                Image.objects.create(album=event.album, image=file, title=file.name)

            return redirect(event.get_absolute_url())

    return render(request, 'events/create_event.html', 
        {'event_form': event_form, 'file_form': file_form, 'event': event})

@login_required
def create_event(request):
    event_form = EventForm(request.POST or None, request.FILES or None)
    file_form = MultipleFileForm(files=request.FILES or None)

    if request.method == 'POST':
 
        if event_form.is_valid() and file_form.is_valid():
            event = event_form.save(commit=False)
            event.host = request.user
            event.save()
            # save the individual images
            for file in request.FILES.getlist('gallery'):
                Image.objects.create(album=event.album, image=file, title=file.name)

            return redirect(event.get_absolute_url())

    return render(request, 'events/create_event.html', 
         {'event_form': event_form, 'file_form': file_form})

@login_required
def remove_eventrun(request, pk):
	eventrun = get_object_or_404(EventRun, pk=pk)
	eventrun.delete()
	return HttpResponseRedirect(reverse('events:eventRuns'))

@login_required
def update_eventrun(request, pk):
	eventrun = get_object_or_404(EventRun, pk=pk)
	if request.method == 'POST':
		form = EventRunForm(request.POST, instance=eventrun)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('events:eventRuns'))
	else:
		form = EventRunForm(instance=eventrun)
	return render(request, 'events/update_eventrun.html', {'form': form})

@login_required
def create_eventrun(request):
	if request.method == 'POST':
		form = EventRunForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('events:eventRuns'))
	else:
		form = EventRunForm()
	return render(request, 'events/create_eventrun.html', {'form': form})

explorea/templates/events/create_event.html
{% extends 'base.html' %}
{% load event_tags %}

{% block title %}
	<title>Event Detail</title>
{% endblock title %}

{% block content %}
<div>

  <h2>Edit event {{ event.name }}</h2>
  
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {% for field in event_form.invisible_fields %}
        {% for error in field.errors %}
          <p>{{error}}</p>
        {% endfor %}
    {% endfor %}

    {% for field in event_form.visible_fields %}
        <p>{{ field.label_tag}}{{ field }}</p>
        {% for error in field.errors %}
            {{ error }}
        {% endfor %}      
    {% endfor %}

    {{ file_form.as_p }}
    <button type="submit">Save</button>

  </form>
  
</div>
{% endblock content %}

explorea/templates/events/create_eventrun.html
{% extends 'base.html' %} 

{% block title %}<title>Create EventRun</title>{% endblock title %}

{% block content %}

<div>
  <h2>Create Event Run</h2>
  
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
  </form>
  
</div>

{% endblock %}

explorea/templates/events/eventRun_listing.html
{% extends 'base.html' %}
{% block title %}
 	<title>Event Runs</title>
{% endblock title %}

{% block content %}
<h2>All Event Runs:</h2>
<ul>
	{% for eventRun in eventRuns %}
		<li>{{ eventRun.event }} - {{ eventRun.date }} - {{ eventRun.seats_available }} - {{ eventRun.price }}
		 <a href="{% url 'events:update_eventrun' eventRun.pk %}">Update</a> <a href="{% url 'events:remove_eventrun' eventRun.pk %}">Remove</a></li>
	{% endfor %}
</ul>

{% endblock content %}

explorea/templates/events/event_detail.html
{% extends 'base.html' %}
{% load event_tags %}

{% block title %}
	<title>Event Detail</title>
{% endblock title %}

{% block content %}
<h2>{{ event.name }} | <a href="{% url 'events:update_event' event.slug %}">UPDATE</a></h2>
<p>host: {{ event.host }}</p>
<p>Description: {{ event.description }}</p>
<p>Location: {{ event.location }}</p>
<p>Category: {{ event.category }}</p>
<div class="main-image">
    {% if event|has:'main_image' %}
    <img src="{{ event.main_image.url }}">
    {% else %}
    <div class="not-available"></div>
    {% endif %}
</div>
<!--Image slideshow-->
<div class="owl-carousel">
    <span class="owl-nav"></span>
    <span class="owl-prev"></span>
{% for image in event.album.image_set.all %}
<img src="{{ image.image.url }}" alt="{{ image.title }}">
{% endfor %}
</div>
<br />
<br />
<p><strong>Current Event Runs</strong></p>
{% if runs %}
    <ul>
     	{% for run in runs %}
    	<li>{{ run.date }} - {{ run.seats_available }} available seats, for only ${{ run.price }}</li>

    	{% endfor %}
     </ul>
{% else %}
<p>There are not events taking place for this event</p>
{% endif %}

   

{% endblock content %}

explorea/templates/events/event_listing.html
{% extends 'base.html' %}
{% load event_tags %}

{% block title %}
<title>Event Listing</title>
{% endblock title %}

{% block content %}
<div class="thin-banner">
    <h1>What do we have here ...</h1>
</div>

<form class="event-filters"  method="GET">
    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
    {% endfor %}

    {% for field in filter_form.visible_fields %}
        <div class="form-filter">
            {{ field.label_tag }} {{ field }}
            <div class="errors">
                {% for error in field.errors %}
                    <div class="error">{{ error }}</div>
                {% endfor %}
            </div>
        </div>
        
    {% endfor %}
    <button type="submit">Filter</button>
</form>

<div class="event-category-filters">
    <!--by clicking these buttons we should be taken to event listing, that show us only events of the given event category-->
    <a class="button-gold" href="{% url 'events:events_by_category' 'fun' %}">Fun</a>
    <a class="button-gold" href="{% url 'events:events_by_category' 'experience' %}">Experience</a>
    <a class="button-gold" href="{% url 'events:events_by_category' 'sights' %}">Sights</a>
    <a class="button-gold" href="{% url 'events:events_by_category' 'relax' %}">Relax</a>
</div>

<div class="tile-container">
    {% if event_runs %}
    <div class="tile-grid">

            {% for eventrun in event_runs %}
                <a class="event-tile" href="{{ eventrun.event.get_absolute_url }}">
                   {% if eventrun.event|has:'thumbnail' %}
                        <img src="{{ eventrun.event.thumbnail.url }}">
                    {% else %}
                    <div class="not-available"></div>
                    {% endif %}
                    <div class="event-details">
                        <p>{{ eventrun.event.host }}</p>
                        <p>{{ eventrun.event.name }}</p>
                        <p>{{ eventrun.event.location}}</p>
                        <p><strong>Next:</strong> {{ eventrun.date }}</p>
                        <p><strong>Price:</strong> $ {{ eventrun.price }}</p>
                        <p><strong>Seats:</strong> {{ eventrun.seats_available }}</p>
                        <hr>
                        <p><strong>Price From:</strong> $ {{ eventrun.event.eventrun_set.all|active|min_attr_value:"price" }}</p>
                        <p><strong>Seats Up To:</strong> {{ eventrun.event.eventrun_set.all|active|max_attr_value:"seats_available" }}</p>
                    </div>
                </a>        
            {% endfor %}

    {% else %}
        <div class="info empty-search">No events found ...</div>
    {% endif %}
    </div>
</div>
{% include 'pagination.html' with page=event_runs %}

{% endblock content %}

explorea/templates/events/index.html
{% extends 'base.html' %}

{% block title %}
<title>Index</title>
{% endblock title %}

{% block content %}

<div class="main-banner">
    <p class="claim">Let's do something</p>
    <a href="{% url 'events:events_by_category' 'fun' %}">Fun</a>
    <a href="{% url 'events:events_by_category' 'experience' %}">Experience</a>
    <a href="{% url 'events:events_by_category' 'sights' %}">Sights</a>
    <a href="{% url 'events:events_by_category' 'relax' %}">Relax</a>
</div>


{% endblock content %}

explorea/templates/events/myevents_listing.html
{% extends 'base.html' %}

{% block title %}
	<title>My Events Listing</title>
{% endblock title %}

{% block content %}
	<h2>My Events:</h2>
    <ul>
    {% for event in events %}
    	<li><a href="{% url 'events:detail' event.pk %}">{{ event.name }}</a> <a href="{% url 'events:update_event' event.pk %}">Update</a>
    		<a href="{% url 'events:delete_event' event.pk %}">Delete</a></li>
    {% endfor %}
    </ul>
{% endblock content %}

explorea/templates/events/update_eventrun.html
{% extends 'base.html' %} 

{% block title %}<title>Update Event Run</title>{% endblock title %}

{% block content %}

<div>
  <h2>Update Event Run</h2>
  
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
  </form>
  
</div>

{% endblock %}